<?php

declare(strict_types=1);

// Code generated by Scalar SDK Generator. DO NOT EDIT.
require_once __DIR__ . '/../vendor/autoload.php';

use DemoAPIScalarGalaxy\Client;

// Smoke test: calls every generated operation once to confirm the SDK can reach each endpoint.
// Run it from this repo with `php tests/smoke-test.php`. The generator also runs this file
// against a mock server and reads the JSON report produced via SCALAR_SMOKE_REPORT.
$client = new Client(requestOptions: ['maxRetries' => 0, 'timeout' => 30.0]);

$cases = [
    [
        'operation' => 'create',
        'method' => 'POST',
        'path' => '/planets',
        'label' => 'required params',
        'run' => static function () use ($client): void {
            $client->planets->create(name: 'Mars', type: 'terrestrial');
        },
    ],
    [
        'operation' => 'create',
        'method' => 'POST',
        'path' => '/planets',
        'label' => 'all params',
        'run' => static function () use ($client): void {
            $client->planets->create(
                name: 'Mars',
                type: 'terrestrial',
                atmosphere: [[]],
                creator: ['name' => 'Marc'],
                description: 'The red planet',
                discoveredAt: new \DateTimeImmutable('1610-01-07T00:00:00Z'),
                failureCallbackURL: 'https://example.com/webhook',
                habitabilityIndex: 0.68,
                image: 'https://cdn.scalar.com/photos/mars.jpg',
                physicalProperties: [
                    'mass' => 0.107,
                    'radius' => 0.532,
                    'gravity' => 0.378,
                    'temperature' => [],
                ],
                satellites: [['name' => 'Phobos', 'type' => 'moon']],
                successCallbackURL: 'https://example.com/webhook',
                tags: [''],
            );
        },
    ],
    [
        'operation' => 'retrieve',
        'method' => 'GET',
        'path' => '/planets/{planetId}',
        'run' => static function () use ($client): void {
            $client->planets->retrieve(1);
        },
    ],
    [
        'operation' => 'update',
        'method' => 'PUT',
        'path' => '/planets/{planetId}',
        'label' => 'required params',
        'run' => static function () use ($client): void {
            $client->planets->update(1, name: 'Mars', type: 'terrestrial');
        },
    ],
    [
        'operation' => 'update',
        'method' => 'PUT',
        'path' => '/planets/{planetId}',
        'label' => 'all params',
        'run' => static function () use ($client): void {
            $client->planets->update(
                1,
                name: 'Mars',
                type: 'terrestrial',
                atmosphere: [[]],
                creator: ['name' => 'Marc'],
                description: 'The red planet',
                discoveredAt: new \DateTimeImmutable('1610-01-07T00:00:00Z'),
                failureCallbackURL: 'https://example.com/webhook',
                habitabilityIndex: 0.68,
                image: 'https://cdn.scalar.com/photos/mars.jpg',
                physicalProperties: [
                    'mass' => 0.107,
                    'radius' => 0.532,
                    'gravity' => 0.378,
                    'temperature' => [],
                ],
                satellites: [['name' => 'Phobos', 'type' => 'moon']],
                successCallbackURL: 'https://example.com/webhook',
                tags: [''],
            );
        },
    ],
    [
        'operation' => 'list',
        'method' => 'GET',
        'path' => '/planets',
        'run' => static function () use ($client): void {
            $client->planets->list(limit: 10, offset: 0);
        },
    ],
    [
        'operation' => 'delete',
        'method' => 'DELETE',
        'path' => '/planets/{planetId}',
        'run' => static function () use ($client): void {
            $client->planets->delete(1);
        },
    ],
    [
        'operation' => 'uploadImage',
        'method' => 'POST',
        'path' => '/planets/{planetId}/image',
        'label' => 'required params',
        'run' => static function () use ($client): void {
            $client->planets->uploadImage(1);
        },
    ],
    [
        'operation' => 'uploadImage',
        'method' => 'POST',
        'path' => '/planets/{planetId}/image',
        'label' => 'all params',
        'run' => static function () use ($client): void {
            $client->planets->uploadImage(1, image: 'smoke-test');
        },
    ],
    [
        'operation' => 'create',
        'method' => 'POST',
        'path' => '/celestial-bodies',
        'label' => 'required params',
        'run' => static function () use ($client): void {
            $client->celestialBodies->create(name: 'Mars', type: 'terrestrial');
        },
    ],
    [
        'operation' => 'create',
        'method' => 'POST',
        'path' => '/celestial-bodies',
        'label' => 'all params',
        'run' => static function () use ($client): void {
            $client->celestialBodies->create(
                name: 'Mars',
                type: 'terrestrial',
                atmosphere: [[]],
                creator: ['name' => 'Marc'],
                description: 'The red planet',
                discoveredAt: new \DateTimeImmutable('1610-01-07T00:00:00Z'),
                failureCallbackURL: 'https://example.com/webhook',
                habitabilityIndex: 0.68,
                image: 'https://cdn.scalar.com/photos/mars.jpg',
                physicalProperties: [
                    'mass' => 0.107,
                    'radius' => 0.532,
                    'gravity' => 0.378,
                    'temperature' => [],
                ],
                satellites: [['name' => 'Phobos', 'type' => 'moon']],
                successCallbackURL: 'https://example.com/webhook',
                tags: [''],
                diameter: 22.2,
                orbit: [
                    'planetId' => 1,
                    'orbitalPeriod' => 0.319,
                    'distance' => 9376,
                ],
            );
        },
    ],
    [
        'operation' => 'createToken',
        'method' => 'POST',
        'path' => '/auth/token',
        'run' => static function () use ($client): void {
            $client->authentication->createToken(
                email: 'marc@scalar.com',
                password: 'i-love-scalar',
            );
        },
    ],
    [
        'operation' => 'createUser',
        'method' => 'POST',
        'path' => '/user/signup',
        'run' => static function () use ($client): void {
            $client->authentication->createUser(
                email: 'marc@scalar.com',
                password: 'i-love-scalar',
                name: 'Marc',
            );
        },
    ],
    [
        'operation' => 'listMe',
        'method' => 'GET',
        'path' => '/me',
        'run' => static function () use ($client): void {
            $client->authentication->listMe();
        },
    ],
];

$filter = getenv('SCALAR_SMOKE_FILTER') ?: '';
$needles = array_filter(array_map('trim', explode(',', $filter)));
$selected = $needles === []
    ? $cases
    : array_values(array_filter($cases, static function (array $case) use (
        $needles,
    ): bool {
        foreach ($needles as $needle) {
            if (
                str_contains($case['operation'], $needle)
                || str_contains($case['path'], $needle)
            ) {
                return true;
            }
        }

        return false;
    }));

$results = [];
foreach ($selected as $case) {
    $startedAt = hrtime(true);
    try {
        $case['run']();
        $status = ['status' => 'passed'];
    } catch (\Throwable $error) {
        $status = [
            'status' => 'failed',
            'error' => $error::class . ': ' . $error->getMessage(),
        ];
    }

    $results[] = [
        'operation' => $case['operation'],
        'method' => $case['method'],
        'path' => $case['path'],
        // Present only when the operation contributed both of its calls; a single-case
        // operation reports exactly as it did before there were two.
        ...(isset($case['label']) ? ['label' => $case['label']] : []),
        'durationMs' => (int) ((hrtime(true) - $startedAt) / 1e6),
        ...$status,
    ];
}

$failed = array_values(array_filter(
    $results,
    static fn(array $result): bool => $result['status'] === 'failed',
));
$report = getenv('SCALAR_SMOKE_REPORT');
if ($report) {
    file_put_contents($report, json_encode([
        'total' => count($results),
        'failed' => count($failed),
        'results' => $results,
    ]));
} else {
    foreach ($results as $result) {
        $suffix = isset($result['label']) ? ' [' . $result['label'] . ']' : '';
        $line = sprintf(
            '%s %s%s (%s %s) %dms',
            strtoupper($result['status']),
            $result['operation'],
            $suffix,
            $result['method'],
            $result['path'],
            $result['durationMs'],
        );
        fwrite(
            $result['status'] === 'passed' ? STDOUT : STDERR,
            $line . PHP_EOL,
        );
        if ($result['status'] === 'failed') {
            fwrite(STDERR, $result['error'] . PHP_EOL);
        }
    }
}

exit(count($failed) > 0 || count($results) === 0 ? 1 : 0);
